name: md_pipeline

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - mdanalysis
  - pyyaml

  # Optional analyses
  - deeptime
  - umap-learn
  - hdbscan
